### ISSUE TITLE
Accept all valid characters as hyphenations

### ISSUE THREAD

**Issue by egli** [sbsdev/hyphen-keeper#2]
Valid characters according to the ones defined in https://github.com/sbsdev/sbs-braille-tables/blob/master/tables/sbs-de-core6.cti#L60 and the [APOSTROPHE](https://www.fileformat.info/info/unicode/char/0031/index.htm)

**Comment by egli** [comment]
Use http://www.fileformat.info/info/unicode/block/latin_extended_a/list.htm in the regexp

**Comment by egli** [comment]
Also add APOSTROPHE to the regexp

**Comment by mixa72** [comment]
Dieses Feature wurde aufgesplittet. Die Implementierung der Eingabe von Apostroph-Zeichen steht noch aus. (cf. https://github.com/sbsdev/hyphen-keeper/issues/3)
