### ISSUE TITLE
Türkisches kleines ı nicht in der Eingabe zulassen

### ISSUE THREAD

**Issue by mixa72** [sbsdev/hyphen-keeper#4]
Momentan bewirkt die Eingabe des kleinen türkischen ı (\x0131) ins Trenntool einen Absturz, d.h. das erzeugte Braille-File ist leer, wenn sich im XML-File das entsprechende Wort befindet. Dies soll unbedingt verhindert werden.

Mögliche Ansätze:
1) entweder Trenntool erweitern/reparieren, so dass es das Zeichen ı auch ünterstützt
2) oder Eingabe von ı im Trenntool nicht zulassen

**Comment by egli** [comment]
Bert says that libhyphen should also support utf-8 hyphenation tables, so we might be able to support that. Currently `hyphen-keeper` encodes the hyphenation tables as ISO-8859-1.

**Comment by mixa72** [comment]
Absturz wird nur durch Zeichen İ bewirkt (nur bei eingeschalteter Trennung). Zeichen ı funktioniert im Hyphenation-Tool. Eingabe kann bestehen bleiben.
